import type { VoiceOption } from '../../state/types';

// Extract locale and name from full value like "ru-RU, DmitryNeural"
function parseVoice(fullValue: string): VoiceOption {
  const [locale, name] = fullValue.split(', ');
  return { locale, name, fullValue };
}

export const voices: VoiceOption[] = [
  // Russian (prioritized)
  'ru-RU, DmitryNeural',
  'ru-RU, SvetlanaNeural',
  // Multilingual
  'en-AU, WilliamMultilingualNeural',
  'en-US, AndrewMultilingualNeural',
  'en-US, AvaMultilingualNeural',
  'en-US, BrianMultilingualNeural',
  'en-US, EmmaMultilingualNeural',
  'fr-FR, VivienneMultilingualNeural',
  'fr-FR, RemyMultilingualNeural',
  'de-DE, SeraphinaMultilingualNeural',
  'de-DE, FlorianMultilingualNeural',
  'it-IT, GiuseppeMultilingualNeural',
  'ko-KR, HyunsuMultilingualNeural',
  'pt-BR, ThalitaMultilingualNeural',
  // Afrikaans
  'af-ZA, AdriNeural',
  'af-ZA, WillemNeural',
  // Albanian
  'sq-AL, AnilaNeural',
  'sq-AL, IlirNeural',
  // Amharic
  'am-ET, AmehaNeural',
  'am-ET, MekdesNeural',
  // Arabic
  'ar-DZ, AminaNeural',
  'ar-DZ, IsmaelNeural',
  'ar-BH, AliNeural',
  'ar-BH, LailaNeural',
  'ar-EG, SalmaNeural',
  'ar-EG, ShakirNeural',
  'ar-IQ, BasselNeural',
  'ar-IQ, RanaNeural',
  'ar-JO, SanaNeural',
  'ar-JO, TaimNeural',
  'ar-KW, FahedNeural',
  'ar-KW, NouraNeural',
  'ar-LB, LaylaNeural',
  'ar-LB, RamiNeural',
  'ar-LY, ImanNeural',
  'ar-LY, OmarNeural',
  'ar-MA, JamalNeural',
  'ar-MA, MounaNeural',
  'ar-OM, AbdullahNeural',
  'ar-OM, AyshaNeural',
  'ar-QA, AmalNeural',
  'ar-QA, MoazNeural',
  'ar-SA, HamedNeural',
  'ar-SA, ZariyahNeural',
  'ar-SY, AmanyNeural',
  'ar-SY, LaithNeural',
  'ar-TN, HediNeural',
  'ar-TN, ReemNeural',
  'ar-AE, FatimaNeural',
  'ar-AE, HamdanNeural',
  'ar-YE, MaryamNeural',
  'ar-YE, SalehNeural',
  // Azerbaijani
  'az-AZ, BabekNeural',
  'az-AZ, BanuNeural',
  // Bengali
  'bn-BD, NabanitaNeural',
  'bn-BD, PradeepNeural',
  'bn-IN, BashkarNeural',
  'bn-IN, TanishaaNeural',
  // Bosnian
  'bs-BA, VesnaNeural',
  'bs-BA, GoranNeural',
  // Bulgarian
  'bg-BG, BorislavNeural',
  'bg-BG, KalinaNeural',
  // Burmese
  'my-MM, NilarNeural',
  'my-MM, ThihaNeural',
  // Catalan
  'ca-ES, EnricNeural',
  'ca-ES, JoanaNeural',
  // Chinese
  'zh-HK, HiuGaaiNeural',
  'zh-HK, HiuMaanNeural',
  'zh-HK, WanLungNeural',
  'zh-CN, XiaoxiaoNeural',
  'zh-CN, XiaoyiNeural',
  'zh-CN, YunjianNeural',
  'zh-CN, YunxiNeural',
  'zh-CN, YunxiaNeural',
  'zh-CN, YunyangNeural',
  'zh-CN-liaoning, XiaobeiNeural',
  'zh-TW, HsiaoChenNeural',
  'zh-TW, YunJheNeural',
  'zh-TW, HsiaoYuNeural',
  'zh-CN-shaanxi, XiaoniNeural',
  // Croatian
  'hr-HR, GabrijelaNeural',
  'hr-HR, SreckoNeural',
  // Czech
  'cs-CZ, AntoninNeural',
  'cs-CZ, VlastaNeural',
  // Danish
  'da-DK, ChristelNeural',
  'da-DK, JeppeNeural',
  // Dutch
  'nl-BE, ArnaudNeural',
  'nl-BE, DenaNeural',
  'nl-NL, ColetteNeural',
  'nl-NL, FennaNeural',
  'nl-NL, MaartenNeural',
  // English
  'en-AU, NatashaNeural',
  'en-CA, ClaraNeural',
  'en-CA, LiamNeural',
  'en-HK, YanNeural',
  'en-HK, SamNeural',
  'en-IN, NeerjaExpressiveNeural',
  'en-IN, NeerjaNeural',
  'en-IN, PrabhatNeural',
  'en-IE, ConnorNeural',
  'en-IE, EmilyNeural',
  'en-KE, AsiliaNeural',
  'en-KE, ChilembaNeural',
  'en-NZ, MitchellNeural',
  'en-NZ, MollyNeural',
  'en-NG, AbeoNeural',
  'en-NG, EzinneNeural',
  'en-PH, JamesNeural',
  'en-PH, RosaNeural',
  'en-US, AvaNeural',
  'en-US, AndrewNeural',
  'en-US, EmmaNeural',
  'en-US, BrianNeural',
  'en-SG, LunaNeural',
  'en-SG, WayneNeural',
  'en-ZA, LeahNeural',
  'en-ZA, LukeNeural',
  'en-TZ, ElimuNeural',
  'en-TZ, ImaniNeural',
  'en-GB, LibbyNeural',
  'en-GB, MaisieNeural',
  'en-GB, RyanNeural',
  'en-GB, SoniaNeural',
  'en-GB, ThomasNeural',
  'en-US, AnaNeural',
  'en-US, AriaNeural',
  'en-US, ChristopherNeural',
  'en-US, EricNeural',
  'en-US, GuyNeural',
  'en-US, JennyNeural',
  'en-US, MichelleNeural',
  'en-US, RogerNeural',
  'en-US, SteffanNeural',
  // Estonian
  'et-EE, AnuNeural',
  'et-EE, KertNeural',
  // Filipino
  'fil-PH, AngeloNeural',
  'fil-PH, BlessicaNeural',
  // Finnish
  'fi-FI, HarriNeural',
  'fi-FI, NooraNeural',
  // French
  'fr-BE, CharlineNeural',
  'fr-BE, GerardNeural',
  'fr-CA, ThierryNeural',
  'fr-CA, AntoineNeural',
  'fr-CA, JeanNeural',
  'fr-CA, SylvieNeural',
  'fr-FR, DeniseNeural',
  'fr-FR, EloiseNeural',
  'fr-FR, HenriNeural',
  'fr-CH, ArianeNeural',
  'fr-CH, FabriceNeural',
  // Galician
  'gl-ES, RoiNeural',
  'gl-ES, SabelaNeural',
  // Georgian
  'ka-GE, EkaNeural',
  'ka-GE, GiorgiNeural',
  // German
  'de-AT, IngridNeural',
  'de-AT, JonasNeural',
  'de-DE, AmalaNeural',
  'de-DE, ConradNeural',
  'de-DE, KatjaNeural',
  'de-DE, KillianNeural',
  'de-CH, JanNeural',
  'de-CH, LeniNeural',
  // Greek
  'el-GR, AthinaNeural',
  'el-GR, NestorasNeural',
  // Gujarati
  'gu-IN, DhwaniNeural',
  'gu-IN, NiranjanNeural',
  // Hebrew
  'he-IL, AvriNeural',
  'he-IL, HilaNeural',
  // Hindi
  'hi-IN, MadhurNeural',
  'hi-IN, SwaraNeural',
  // Hungarian
  'hu-HU, NoemiNeural',
  'hu-HU, TamasNeural',
  // Icelandic
  'is-IS, GudrunNeural',
  'is-IS, GunnarNeural',
  // Indonesian
  'id-ID, ArdiNeural',
  'id-ID, GadisNeural',
  // Inuktitut
  'iu-Latn-CA, SiqiniqNeural',
  'iu-Latn-CA, TaqqiqNeural',
  'iu-Cans-CA, SiqiniqNeural',
  'iu-Cans-CA, TaqqiqNeural',
  // Irish
  'ga-IE, ColmNeural',
  'ga-IE, OrlaNeural',
  // Italian
  'it-IT, DiegoNeural',
  'it-IT, ElsaNeural',
  'it-IT, IsabellaNeural',
  // Japanese
  'ja-JP, KeitaNeural',
  'ja-JP, NanamiNeural',
  // Javanese
  'jv-ID, DimasNeural',
  'jv-ID, SitiNeural',
  // Kannada
  'kn-IN, GaganNeural',
  'kn-IN, SapnaNeural',
  // Kazakh
  'kk-KZ, AigulNeural',
  'kk-KZ, DauletNeural',
  // Khmer
  'km-KH, PisethNeural',
  'km-KH, SreymomNeural',
  // Korean
  'ko-KR, InJoonNeural',
  'ko-KR, SunHiNeural',
  // Lao
  'lo-LA, ChanthavongNeural',
  'lo-LA, KeomanyNeural',
  // Latvian
  'lv-LV, EveritaNeural',
  'lv-LV, NilsNeural',
  // Lithuanian
  'lt-LT, LeonasNeural',
  'lt-LT, OnaNeural',
  // Macedonian
  'mk-MK, AleksandarNeural',
  'mk-MK, MarijaNeural',
  // Malay
  'ms-MY, OsmanNeural',
  'ms-MY, YasminNeural',
  // Malayalam
  'ml-IN, MidhunNeural',
  'ml-IN, SobhanaNeural',
  // Maltese
  'mt-MT, GraceNeural',
  'mt-MT, JosephNeural',
  // Marathi
  'mr-IN, AarohiNeural',
  'mr-IN, ManoharNeural',
  // Mongolian
  'mn-MN, BataaNeural',
  'mn-MN, YesuiNeural',
  // Nepali
  'ne-NP, HemkalaNeural',
  'ne-NP, SagarNeural',
  // Norwegian
  'nb-NO, FinnNeural',
  'nb-NO, PernilleNeural',
  // Pashto
  'ps-AF, GulNawazNeural',
  'ps-AF, LatifaNeural',
  // Persian
  'fa-IR, DilaraNeural',
  'fa-IR, FaridNeural',
  // Polish
  'pl-PL, MarekNeural',
  'pl-PL, ZofiaNeural',
  // Portuguese
  'pt-BR, AntonioNeural',
  'pt-BR, FranciscaNeural',
  'pt-PT, DuarteNeural',
  'pt-PT, RaquelNeural',
  // Romanian
  'ro-RO, AlinaNeural',
  'ro-RO, EmilNeural',
  // Serbian
  'sr-RS, NicholasNeural',
  'sr-RS, SophieNeural',
  // Sinhala
  'si-LK, SameeraNeural',
  'si-LK, ThiliniNeural',
  // Slovak
  'sk-SK, LukasNeural',
  'sk-SK, ViktoriaNeural',
  // Slovenian
  'sl-SI, PetraNeural',
  'sl-SI, RokNeural',
  // Somali
  'so-SO, MuuseNeural',
  'so-SO, UbaxNeural',
  // Spanish
  'es-AR, ElenaNeural',
  'es-AR, TomasNeural',
  'es-BO, MarceloNeural',
  'es-BO, SofiaNeural',
  'es-CL, CatalinaNeural',
  'es-CL, LorenzoNeural',
  'es-CO, GonzaloNeural',
  'es-CO, SalomeNeural',
  'es-ES, XimenaNeural',
  'es-CR, JuanNeural',
  'es-CR, MariaNeural',
  'es-CU, BelkysNeural',
  'es-CU, ManuelNeural',
  'es-DO, EmilioNeural',
  'es-DO, RamonaNeural',
  'es-EC, AndreaNeural',
  'es-EC, LuisNeural',
  'es-SV, LorenaNeural',
  'es-SV, RodrigoNeural',
  'es-GQ, JavierNeural',
  'es-GQ, TeresaNeural',
  'es-GT, AndresNeural',
  'es-GT, MartaNeural',
  'es-HN, CarlosNeural',
  'es-HN, KarlaNeural',
  'es-MX, DaliaNeural',
  'es-MX, JorgeNeural',
  'es-NI, FedericoNeural',
  'es-NI, YolandaNeural',
  'es-PA, MargaritaNeural',
  'es-PA, RobertoNeural',
  'es-PY, MarioNeural',
  'es-PY, TaniaNeural',
  'es-PE, AlexNeural',
  'es-PE, CamilaNeural',
  'es-PR, KarinaNeural',
  'es-PR, VictorNeural',
  'es-ES, AlvaroNeural',
  'es-ES, ElviraNeural',
  'es-US, AlonsoNeural',
  'es-US, PalomaNeural',
  'es-UY, MateoNeural',
  'es-UY, ValentinaNeural',
  'es-VE, PaolaNeural',
  'es-VE, SebastianNeural',
  // Sundanese
  'su-ID, JajangNeural',
  'su-ID, TutiNeural',
  // Swahili
  'sw-KE, RafikiNeural',
  'sw-KE, ZuriNeural',
  'sw-TZ, DaudiNeural',
  'sw-TZ, RehemaNeural',
  // Swedish
  'sv-SE, MattiasNeural',
  'sv-SE, SofieNeural',
  // Tamil
  'ta-IN, PallaviNeural',
  'ta-IN, ValluvarNeural',
  'ta-MY, KaniNeural',
  'ta-MY, SuryaNeural',
  'ta-SG, AnbuNeural',
  'ta-SG, VenbaNeural',
  'ta-LK, KumarNeural',
  'ta-LK, SaranyaNeural',
  // Telugu
  'te-IN, MohanNeural',
  'te-IN, ShrutiNeural',
  // Thai
  'th-TH, NiwatNeural',
  'th-TH, PremwadeeNeural',
  // Turkish
  'tr-TR, EmelNeural',
  'tr-TR, AhmetNeural',
  // Ukrainian
  'uk-UA, OstapNeural',
  'uk-UA, PolinaNeural',
  // Urdu
  'ur-IN, GulNeural',
  'ur-IN, SalmanNeural',
  'ur-PK, AsadNeural',
  'ur-PK, UzmaNeural',
  // Uzbek
  'uz-UZ, MadinaNeural',
  'uz-UZ, SardorNeural',
  // Vietnamese
  'vi-VN, HoaiMyNeural',
  'vi-VN, NamMinhNeural',
  // Welsh
  'cy-GB, AledNeural',
  'cy-GB, NiaNeural',
  // Zulu
  'zu-ZA, ThandoNeural',
  'zu-ZA, ThembaNeural',
].map(parseVoice);

export default voices;
